version: '3.9'
name: 'reth'

services:
  rethn1:
    restart: unless-stopped
    image: xreth
    ports:
      - '9001:9001' # metrics
      - '30313:30303' # eth/66 peering
      - '11545:8545' # rpc
      - '11551:8551' # engine
    networks:
      app_net:
        ipv4_address: 10.5.0.5
    volumes:
      - /data/rethdatas/n1:/app/rethdata
      - /data/rethlogs/n1:/app/rethlogs
    command: >
      node
      --datadir=rethdata
      --chain=/app/genesis.json
      --http
      --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.port=8545
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=net,eth
      --port=30303
      --authrpc.port=8551
      --authrpc.addr=0.0.0.0
      --authrpc.jwtsecret=/app/secrets/jwt.hex
      --log.file.directory=rethlogs
      --log.file.filter=info
      --p2p-secret-key=/app/secrets/p2pn1.hex
      --ipcdisable
      --bootnodes=enode://3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddbf3f8db23956ce65cc97e0099103d97576bb8ee030d33e099363de4ddf88a8b44@10.5.0.6:30303,enode://6202a42963acfe9ed6bdb11e1cacdb61fcb5fc0a967972acf675286d3a546276c633ad0911a8bb7ecb2ad5dded80059f013187a8bc69e5bc6eba18410d8b4a91@10.5.0.7:30303,enode://fecf8e7cf8ac4c9eef1bbc8c7c10ee72999e155a3d6c51b6026a55e633c0f5d250d5ad437b3552f8f11144f9a2029736e46d63a2d3551b156aac9bff9a6e22bd@10.5.0.8:30303
    
  rethn2:
    restart: unless-stopped
    image: xreth
    ports:
      - '9002:9001' # metrics
      - '30323:30303' # eth/66 peering
      - '12545:8545' # rpc
      - '12551:8551' # engine
    networks:
      app_net:
        ipv4_address: 10.5.0.6
    volumes:
      - /data/rethdatas/n2:/app/rethdata
      - /data/rethlogs/n2:/app/rethlogs
    command: >
      node
      --datadir=rethdata
      --chain=/app/genesis.json
      --http
      --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.port=8545
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=net,eth
      --port=30303
      --authrpc.port=8551
      --authrpc.addr=0.0.0.0
      --authrpc.jwtsecret=/app/secrets/jwt.hex
      --log.file.directory=rethlogs
      --log.file.filter=info
      --p2p-secret-key=/app/secrets/p2pn2.hex
      --ipcdisable
      --bootnodes=enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@10.5.0.5:30303,enode://6202a42963acfe9ed6bdb11e1cacdb61fcb5fc0a967972acf675286d3a546276c633ad0911a8bb7ecb2ad5dded80059f013187a8bc69e5bc6eba18410d8b4a91@10.5.0.7:30303,enode://fecf8e7cf8ac4c9eef1bbc8c7c10ee72999e155a3d6c51b6026a55e633c0f5d250d5ad437b3552f8f11144f9a2029736e46d63a2d3551b156aac9bff9a6e22bd@10.5.0.8:30303
      
  rethn3:
    restart: unless-stopped
    image: xreth
    ports:
      - '9003:9001' # metrics
      - '30333:30303' # eth/66 peering
      - '13545:8545' # rpc
      - '13551:8551' # engine
    networks:
      app_net:
        ipv4_address: 10.5.0.7
    volumes:
      - /data/rethdatas/n3:/app/rethdata
      - /data/rethlogs/n3:/app/rethlogs
    command: >
      node
      --datadir=rethdata
      --chain=/app/genesis.json
      --http
      --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.port=8545
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=net,eth
      --port=30303
      --authrpc.port=8551
      --authrpc.addr=0.0.0.0
      --authrpc.jwtsecret=/app/secrets/jwt.hex
      --log.file.directory=rethlogs
      --log.file.filter=info
      --p2p-secret-key=/app/secrets/p2pn3.hex
      --ipcdisable
      --bootnodes=enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@10.5.0.5:30303,enode://3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddbf3f8db23956ce65cc97e0099103d97576bb8ee030d33e099363de4ddf88a8b44@10.5.0.6:30303,enode://fecf8e7cf8ac4c9eef1bbc8c7c10ee72999e155a3d6c51b6026a55e633c0f5d250d5ad437b3552f8f11144f9a2029736e46d63a2d3551b156aac9bff9a6e22bd@10.5.0.8:30303


  rethn4:
    restart: unless-stopped
    image: xreth
    ports:
      - '9004:9001' # metrics
      - '30343:30303' # eth/66 peering
      - '14545:8545' # rpc
      - '14551:8551' # engine
    networks:
      app_net:
        ipv4_address: 10.5.0.8
    volumes:
      - /data/rethdatas/n4:/app/rethdata
      - /data/rethlogs/n4:/app/rethlogs
    command: >
      node
      --datadir=rethdata
      --chain=/app/genesis.json
      --http
      --http.api=admin,net,eth,web3,txpool,rpc,reth,debug,trace,ots
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.port=8545
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=net,eth
      --port=30303
      --authrpc.port=8551
      --authrpc.addr=0.0.0.0
      --authrpc.jwtsecret=/app/secrets/jwt.hex
      --log.file.directory=rethlogs
      --log.file.filter=info
      --p2p-secret-key=/app/secrets/p2pn4.hex
      --ipcdisable
      --bootnodes=enode://23fc99dc5a9411b1f74425cf82d38393f9f0dfa63360848886514eb64f8d61c99a47b52df97afbad20bdbd781086a9e9e228a4d61177d85e28f8cdf5c6ae7738@10.5.0.5:30303,enode://3dafa30585c0db38057f633fd5fc1661648cf9eb9442534bbeee25e998342ddbf3f8db23956ce65cc97e0099103d97576bb8ee030d33e099363de4ddf88a8b44@10.5.0.6:30303,enode://6202a42963acfe9ed6bdb11e1cacdb61fcb5fc0a967972acf675286d3a546276c633ad0911a8bb7ecb2ad5dded80059f013187a8bc69e5bc6eba18410d8b4a91@10.5.0.7:30303


networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1